language: go

os:
  - linux

go:
  - 1.12.x
  - 1.13.x
  - master

before_install:
  # Fetch/build coverage reporting tools
  - go get github.com/mattn/goveralls
  - go install github.com/mattn/goveralls

script:
  - go test -v -covermode=count -coverprofile=coverage.out

after_script:
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
