language: go

os:
  - linux

go:
  - 1.9.x
  - master

script:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go install github.com/mattn/goveralls
  - go test -v -covermode=count -coverprofile=coverage.out

after_script:
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
